//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUTRTV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public int VideoId { get; set; }
        public string Title { get; set; }
        public int Likes { get; set; }
        public double RatePerLike { get; set; }
        public int PresenterId { get; set; }
    
        public virtual Presenter Presenter { get; set; }
    }
}
